sudo: required
services:
- docker
language: python
python:
- '3.5'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- nosetests
- docker build -t my_docker_reposetory/swagger_server .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 my/swagger_server
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag evrancheva/devopsw2 evrancheva/devopsw2
- docker push evrancheva/devopsw2 
env:
  global:
  - secure: DEMrACTB/idXM96fZlDdhyZ0sslbDnfjsL7L2gSpN/gl1vODs5k2TFJri7QBmwUuXXElcrn0MQ/RfZbBJivIJgiHeZB8sIBQ044doTwmEh1OC500YJOEYkHvv2ZQ4aQzjw3fb+ebmAbfSTFyx4/GaYoC3Axt1tAkpedarRRdOPs4MfBqTXRYaO1cfFj2cqE+Yyh0+eZughn2kgFfc0D4b7uz/1VEDM2B1IhJnlGQR+VloM18lb34XZnYtkACAn3Sh17ymasRWZgThno9lN7DxUxpQ5KpRW712n+ksa3M+Fnxxk0sKuFFfng7QY8ddtzKJn86SyeUQ7WAp3zVt6ha0dNW1ymH0xAssGALUF4LEZFP0Kn8e7V6roZWn3JMhVkqv2JJkVDPxdOzGvgJssv6JSLSx3Y4s5Vv5/Cyk2SQrjzcxLLU5PP19ahbtsxuyqbRXbk5b2tg+0INzcbxZSXuLjy/5aww+LDHkHZQ3azms9PsO6ZYLgEWzR4PsApMtSdzAGi9jsB9y+B1/asrdwBndJAloqMNLXuyL/vcoVMdXjh2q6bS98dflmIrLbRJ2uKx0N8Ll9zJDuaZ/sAWwS33PbKk8duxYYekv9pK0/e88ZYURvECw3NUXYR/RFtakpfz2eBVnUHO8FdJxPhbIL/IIx4vrR8YWOtARWUfHMYTljc=
  - secure: yTyGbDtErt6dpQouTs+yhlRLv6y7kTyhpHPwz11zUpBNK9SZZKLG2aqw79sKoCur9LBcC3UcJk9vHPc2h0xf2lTWegAYbXiWkpKlaqYzMr1G8YYtzrN3BuvY4Ogh+fvD8YzWJmra7LnIu8A6su4ih9WJArD824gaOdH1OjYF5m8s9SvgdtfAMX2MyYrCzOSSfChxZsGYF6eSIYQxsIfoMLtrenAbkGvNcTJgPuBN1kdZN1Wyrp1qH56QOsK5Y+5vMIc4FNtCU/h4azvFiClN2aWEhgYALwFHdcNRf1Jjape/W6imJT25ExszpPwmwZqdnSvIYCPFbK6YjvTrPCfTwUOz5yXBl/yCI9GXsdWdE/R/huxPek9HNAXoLopUOhoePqLREOhbVFPn2i71FzIwm46Nc/PCRh1RihNsVmJUJPCN1Ibtl08JIRbW+HWiLHQ59BQXz4LuaTclAqhs722zOGb3AUSRbkdzffy+9emKUexHJtLSM78yebPBJyFr4rX2aevLAXo2dMKk4V5WPRis/Iucs8rYDKD4v+d5ayHqbUOAOfrZtZFoyvTKwBi3MWi4vlnI3JXafNVcyIKrXS70u3Z+FHcYWj8bhj40m60r8wn4TEDUsPzvH+1gSxvLt+zpVLL/L6JP+D11l8eHtMoy+O+Liv1zE3wysalFk834s5c=
